### ISSUE TITLE
Rcon password defaults to 5 letters.

### ISSUE THREAD

**Issue by OMGLent** [GameConnect/SourceBans#66]
Anytime I save my server in the webpanel thing for source bans it reverts the rcon password to 5 letters again. I think is is causing an issue with my server connecting and getting the details from the server.
![before](https://cloud.githubusercontent.com/assets/11316201/6601827/e6170122-c7e5-11e4-876d-a968b255627b.png)
![after](https://cloud.githubusercontent.com/assets/11316201/6601828/e8c23306-c7e5-11e4-8f6c-e4804a6d1a69.png)

**Comment by NomisCZ** [comment]
You must change lenght of rcon column in database. Default value is too small. I recommend 128.
![rcon](https://cloud.githubusercontent.com/assets/7500606/6653631/0ea52310-ca9a-11e4-8719-d44309996214.PNG)

**Comment by OMGLent** [comment]
Even after changing it still goes back to 5 letters like before. However I noticed that the rcon password was working in the mySQL database but for some reason I'm not getting connection to the server. Do I need to install the game files for this to work? I'm running Gmod on the server I have been trying to get the in-game mod to work but anything It Try I always get no database connection please try again even when I have the MySQL server open to wildcard connections.

**Comment by NomisCZ** [comment]
Because SourceBans not displayed value from database, only +-#*_ - default value in PHP file

![2](https://cloud.githubusercontent.com/assets/7500606/6653688/ec3de512-ca9b-11e4-9ee2-c94f55f4b0e9.PNG)

Have you set Admin Server Access to your account in SourceBans? (Admin settings > Your nick > Edit Server Access)

**Comment by OMGLent** [comment]
The issue is I'm getting Error connecting to the server after I update all the server info

**Comment by NomisCZ** [comment]
If you had a wrong rcon password in database ... server could ban IP address of web server. Try restart the server

**Comment by OMGLent** [comment]
I dont think it was wrong thought because it was right in the mysql database. Also yes I have restarted my server multiple times. One of the big issues it getting source mod to working with Garrys mod. Meta mod doesn't support making of gmod vdf files.

**Comment by WildCard65** [comment]
Sourcemod doesn't work with GMOD

**Comment by ErikMinekus** [comment]
SourceBans displays +-#*_ instead of your real RCON password, so that your admins can't go into the HTML and steal it. Rest assured your database contains the real password.

"Error connecting" usually means you need to open the necessary ports, as explained in the [FAQ](https://github.com/GameConnect/SourceBans/wiki/FAQ).
