### ISSUE TITLE
admins.cfg in 2.0.0-dev version dont work more?

### ISSUE THREAD

**Issue by yoberlin** [GameConnect/SourceBans#69]
Hello! I try do add admin, and it work, but on my server admins.cfg file is still empty... Why?

**Comment by DarkDeviL** [comment]
SourceBans is not a synchronizing tool. It doesn't use files, but uses your MySQL database.

**Comment by yoberlin** [comment]
Ok, then why in previous version i have added admins, and after that I have this fields in file admins.cfg in my server sourcemod/cfg folder?

That what you have told me, i can add admin in sourcemod web interface and i dont need to add admins to file admins_simple.cfg?

**Comment by DarkDeviL** [comment]
Previous versions used to keep a backup file; but that file(s) would only used if the connection to your MySQL database could not be established.

And yes, SourceBans kind of takes over the control over your admin and ban management. It is possible to use both things side by side, but there is no reasons to do so in my opinion.
I haven't ever adjusted a single file (with admins) since the day I started using SourceBans.

In theory, the files shouldn't ever have been added if you ask me:
- There's only one in charge of choosing your hosting provider - that would be yourself.
- And there's only one way if your current one is constantly down - switch to something better.

**Comment by ErikMinekus** [comment]
In SourceBans 1, admins were backed up to admins.cfg in case the database server went down (this could be disabled with BackupConfigs 0). But SourceMod already has an admin cache, which is only cleared by sm_reloadadmins or when restarting the game server. So I left out this feature in SourceBans 2.
